name: Vitest and Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # VITEST JOB
  test:
    runs-on: ubuntu-latest
    defaults:
        run:
          working-directory: './frontend'
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn
      - name: Run Vitest
        run: yarn test
  # ESLINT JOB
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
